- name: "Ensure {{ zuul_info_dir }} exists"
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ zuul_info_dir }}"
    state: directory

- name: Collect information about the host
  setup:
  register: setupinfo

- name: Write all ansible vars/facts known for each host
  delegate_to: localhost
  template:
    dest: "{{ zuul_info_dir }}/host-info.{{ inventory_hostname }}.yaml"
    src: templates/host-info.j2
