
- hosts: primary
  become: True

  tasks:
    - name: Create WORKDIR
      file:
        path: /opt/workdir
        state: directory

    - name: Create test-ci-job-pre file
      file:
        path: /opt/workdir/primary-pre.txt
        state: touch
