- name: Set build_log_path fact
  include_role:
    name: set-build-log-path-fact

- name: Create log directories
  file:
    path: "{{ logserver_root }}/{{ build_log_path }}"
    state: directory
    recurse: yes
    mode: 0775

- name: Ensure logs are readable before uploading
  delegate_to: localhost
  command: "chmod -R u=rwX,g=rX,o=rX {{ zuul.executor.log_root }}"

- name: Upload logs to log server
  synchronize:
    src: "{{ zuul.executor.log_root }}/"
    dest: "{{ logserver_root }}/{{ build_log_path }}"
    rsync_opts:
      - "--exclude=job-output.txt"
      - "--exclude=job-output.json"

- name: Archive console log and json job-output
  delegate_to: localhost
  archive:
    path: "{{ zuul.executor.log_root }}/{{ item }}"
  with_items:
    - job-output.txt
    - job-output.json

- name: Upload console log and json output
  synchronize:
    src: "{{ zuul.executor.log_root }}/{{ item }}.gz"
    dest: "{{ logserver_root }}/{{ build_log_path }}/{{ item }}.gz"
    verify_host: true
  with_items:
    - job-output.txt
    - job-output.json

- name: Return log URL to Zuul
  delegate_to: localhost
  zuul_return:
    data:
      zuul:
        log_url: "{{ zuul_log_url }}/{{ build_log_path }}/"