- name: Create SSH private key tempfile
  tempfile:
    state: file
  register: ssh_private_key_tmp

- name: Get id_rsa
  shell: |
    "curl {{ logserver.ssh_private_key }}"
  register: output

- set_fact:
    private_key: "{{ output.stdout_lines }}"

- name: Create SSH private key from secret
  copy:
    content: "{{ private_key }}"
    dest: "{{ ssh_private_key_tmp.path }}"
    mode: 0600

- name: Add logserver ssh key
  command: "ssh-add {{ ssh_private_key_tmp.path }}"

- name: Add logserver to inventory
  add_host:
    name: "{{ logserver.name }}"
    ansible_user: "{{ logserver.ssh_username }}"
    zuul_logserver_project_path: "{{ logserver.path }}/{{ zuul.project.short_name }}"

- name: Add logserver to known hosts
  known_hosts:
    name: "{{ logserver.name }}"
    key: "{{ logserver.ssh_known_hosts }}"