- hosts: all

  tasks:
    - name: Start zuul console
      zuul_console:

- hosts: all
  become: True
  
  tasks:
    - name: Update all repositories
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ linux_package_list }}"

    - name: Print zuul var content
      debug:
        msg: "{{ zuul | to_nice_yaml }}"
