- hosts: all
  pre_tasks:
    # - name: Install python2
    #   raw: sudo apt-get -yy install python

  tasks:
    - name: Start zuul console
      zuul_console:

- hosts: all
  become: True

  tasks:
    - name: Remove lock files - test only
      shell: |
        sudo rm /var/lib/apt/list/lock
        sudo rm /var/cache/apt/archives/lock
        sudo rm /var/lib/dpkg/lock*
        sudo dpkg --configure -a

    - name: Update all repositories
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ linux_package_list }}"

    - name: Print zuul var content
      debug:
        msg: "{{ zuul | to_nice_yaml }}"
